.Dd July 2002
.Dt KISMET_MONITOR 1
.Os "Kismet"
.Sh NAME
.Nm kismet_monitor
.Nd Wireless sniffing and monitoring
.Sh SYNOPSIS
.Ar kismet_monitor
.Op Fl Hh
.Op Fl f Ar file
.Op Fl c Ar capture-source
.Op Fl c Ar channel
.Op Fl O Ar hopper-options
.Sh DESCRIPTION
kismet_monitor is a component of 
kismet which places a wireless card into rfmonitor mode.  rfmon reports the raw packets
seen by the card so that kismet can do passive monitoring.  
kismet_monitor can optionally start the channel hopper
kismet_hopper to rotate through channels rapidly.
.Sh OPTIONS
.Bl -tag -width flag
.It Fl f
Use an alternate config file
.It Fl c
Override capture source lines (engine,interface,type,name).  Refer to kismet.conf(5) for more information.
.It Fl c
Active monitoring mode on a specific channel (default 6)
.It Fl H
Spawn kismet_hopper to rotate between channels.
.It Fl O
Pass extra command options to kismet_hopper
.It Gl v
Print version
.It Fl h
Help
.El
.Sh SEE ALSO
kismet.conf(5), kismet_ui.conf(5), gpsmap(1), kismet(1)
