.TH kismet.conf 5 "February 9, 2004" "" ""
.SH NAME
\fBkismet.conf \fP- Wireless sniffing and monitoring configuration file
\fB
.SH DESCRIPTION
kismet expects a configuration file (/usr/local/etc/kismet.conf by
default) which should conform to the following rules.
A default configuration 
is provided with kismet but it is likely that you will need to 
modify it to suit your hardware and preferences.
.SH CONFIGURATION FILE FORMAT
All entries are of the format directive = value

.SH MORE INFO
The config file comments explain each option, and the README offers more information.

.SH SEE ALSO
\fBkismet_ui.conf\fP(5), \fBkismet_drone.conf\fP(5), \fBgpsmap\fP(1), \fBkismet\fP(1), \fBkismet_drone\fP(1)
