/*
    This file is part of Kismet

    Kismet is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Kismet is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Kismet; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#include "bluetooth_types.h"

std::unordered_map<unsigned int, const char *> bt_major_dev_class{
    {0x00, "Miscellaneous"},
    {0x01, "Computer"},
    {0x02, "Phone"},
    {0x03, "LAN/Network Access Point"},
    {0x04, "Audio/Video"},
    {0x05, "Peripheral (HID)"},
    {0x06, "Imaging"},
    {0x07, "Wearable"},
    {0x08, "Toy"},
    {0x09, "Health"},
    {0x1F, "Uncategorized"},
};

std::unordered_map<unsigned int, const char *> bt_minor_dev_class_computer{
    {0x00, "Uncategorized"},
    {0x01, "Desktop workstation"},
    {0x02, "Server-class computer"},
    {0x03, "Laptop"},
    {0x04, "Handheld PC/PDA (clamshell)"},
    {0x05, "Palm-size PC/PDA"},
    {0x06, "Wearable computer (watch size)"},
    {0x07, "Tablet"},
};

std::unordered_map<unsigned int, const char *> bt_minor_dev_class_phone{
    {0x00, "Uncategorized, code for device not assigned"},
    {0x01, "Cellular"},
    {0x02, "Cordless"},
    {0x03, "Smartphone"},
    {0x04, "Wired modem or voice gateway"},
    {0x05, "Common ISDN access"},
};

std::unordered_map<unsigned int, const char *> bt_minor_dev_class_lan_load{
    {0x00, "0% utilized"},
    {0x01, "1% to 17% utilized"},
    {0x02, "17% to 33% utilized"},
    {0x03, "33% to 50% utilized"},
    {0x04, "50% to 67% utilized"},
    {0x05, "67% to 83% utilized"},
    {0x06, "83% to 99% utilized"},
    {0x07, "No service available"},
};

std::unordered_map<unsigned int, const char *> bt_minor_dev_class_av{
    {0x00, "Uncategorized, code not assigned"},
    {0x01, "Wearable Headset Device"},
    {0x02, "Hands-free Device"},
    {0x04, "Microphone"},
    {0x05, "Loudspeaker"},
    {0x06, "Headphones"},
    {0x07, "Portable Audio"},
    {0x08, "Car audio"},
    {0x09, "Set-top box"},
    {0x0A, "HiFi Audio Device"},
    {0x0B, "VCR"},
    {0x0C, "Video Camera"},
    {0x0D, "Camcorder"},
    {0x0E, "Video Monitor"},
    {0x0F, "Video Display and Loudspeaker"},
    {0x10, "Video Conferencing"},
    {0x12, "Gaming/Toy"},
};

std::unordered_map<unsigned int, const char *> bt_minor_dev_class_peripheral{
    {0x00, "Unknown Peripheral Device"},
    {0x01, "Keyboard"},
    {0x02, "Pointing device"},
    {0x03, "Combo keyboard/pointing device"},
};

std::unordered_map<unsigned int, const char *> bt_minor_dev_type_peripheral{
    {0x00, "Uncategorized device"},
    {0x01, "Joystick"},
    {0x02, "Gamepad"},
    {0x03, "Remote control"},
    {0x04, "Sensing device"},
    {0x05, "Digitizer tablet"},
    {0x06, "Card Reader"},
    {0x07, "Digital Pen"},
    {0x08, "Handheld barcode scanner"},
    {0x09, "Handheld gestural input device"},
};

std::unordered_map<unsigned int, const char *> bt_minor_dev_class_wearable{
    {0x01, "Wristwatch"},
    {0x02, "Pager"},
    {0x03, "Jacket"},
    {0x04, "Helmet"},
    {0x05, "Glasses"},
};

std::unordered_map<unsigned int, const char *> bt_minor_dev_class_toy{
    {0x01, "Robot"},
    {0x02, "Vehicle"},
    {0x03, "Doll / Action figure"},
    {0x04, "Controller"},
    {0x05, "Game"},
};

std::unordered_map<unsigned int, const char *> bt_minor_dev_class_health{
    {0x00, "Undefined"},
    {0x01, "Blood Pressure Monitor"},
    {0x02, "Thermometer"},
    {0x03, "Weighing Scale"},
    {0x04, "Glucose Meter"},
    {0x05, "Pulse Oximeter"},
    {0x06, "Heart/Pulse Rate Monitor"},
    {0x07, "Health Data Display"},
    {0x08, "Step Counter"},
    {0x09, "Body Composition Analyzer"},
    {0x0A, "Peak Flow Monitor"},
    {0x0B, "Medication Monitor"},
    {0x0C, "Knee Prosthesis"},
    {0x0D, "Ankle Prosthesis"},
    {0x0E, "Generic Health Manager"},
    {0x0F, "Personal Mobility Device"},
};

std::unordered_map<unsigned int, const char *> bt_appearance{
    {0, "Unknown"},
    {64, "Generic Phone"},
    {128, "Generic Computer"},
    {192, "Generic Watch"},
    {193, "Watch: Sports Watch"},
    {256, "Generic Clock"},
    {320, "Generic Display"},
    {384, "Generic Remote Control"},
    {448, "Generic Eye-glasses"},
    {512, "Generic Tag"},
    {576, "Generic Keyring"},
    {640, "Generic Media Player"},
    {704, "Generic Barcode Scanner"},
    {768, "Generic Thermometer"},
    {769, "Thermometer: Ear"},
    {832, "Generic Heart rate Sensor"},
    {833, "Heart Rate Sensor: Heart Rate Belt"},
    {896, "Generic Blood Pressure"},
    {897, "Blood Pressure: Arm"},
    {898, "Blood Pressure: Wrist"},
    {960, "Human Interface Device (HID)"},
    {961, "Keyboard"},
    {962, "Mouse"},
    {963, "Joystick"},
    {964, "Gamepad"},
    {965, "Digitizer Tablet"},
    {966, "Card Reader"},
    {967, "Digital Pen"},
    {968, "Barcode Scanner"},
    {1024, "Generic Glucose Meter"},
    {1088, "Generic: Running Walking Sensor"},
    {1089, "Running Walking Sensor: In-Shoe"},
    {1090, "Running Walking Sensor: On-Shoe"},
    {1091, "Running Walking Sensor: On-Hip"},
    {1152, "Generic: Cycling"},
    {1153, "Cycling: Cycling Computer"},
    {1154, "Cycling: Speed Sensor"},
    {1155, "Cycling: Cadence Sensor"},
    {1156, "Cycling: Power Sensor"},
    {1157, "Cycling: Speed and Cadence Sensor"},
    {1216, "Generic Control Device"},
    {1217, "Switch"},
    {1218, "Multi-switch"},
    {1219, "Button"},
    {1220, "Slider"},
    {1221, "Rotary"},
    {1222, "Touch-panel"},
    {1280, "Generic Network Device"},
    {1281, "Access Point"},
    {1344, "Generic Sensor"},
    {1345, "Motion Sensor"},
    {1346, "Air Quality Sensor"},
    {1347, "Temperature Sensor"},
    {1348, "Humidity Sensor"},
    {1349, "Leak Sensor"},
    {1350, "Smoke Sensor"},
    {1351, "Occupancy Sensor"},
    {1352, "Contact Sensor"},
    {1353, "Carbon Monoxide Sensor"},
    {1354, "Carbon Dioxide Sensor"},
    {1355, "Ambient Light Sensor"},
    {1356, "Energy Sensor"},
    {1357, "Color Light Sensor"},
    {1358, "Rain Sensor"},
    {1359, "Fire Sensor"},
    {1360, "Wind Sensor"},
    {1361, "Proximity Sensor"},
    {1362, "Multi-Sensor"},
    {1408, "Generic Light Fixtures"},
    {1409, "Wall Light"},
    {1410, "Ceiling Light"},
    {1411, "Floor Light"},
    {1412, "Cabinet Light"},
    {1413, "Desk Light"},
    {1414, "Troffer Light"},
    {1415, "Pendant Light"},
    {1416, "In-ground Light"},
    {1417, "Flood Light"},
    {1418, "Underwater Light"},
    {1419, "Bollard with Light"},
    {1420, "Pathway Light"},
    {1421, "Garden Light"},
    {1422, "Pole-top Light"},
    {1423, "Spotlight"},
    {1424, "Linear Light"},
    {1425, "Street Light"},
    {1426, "Shelves Light"},
    {1427, "High-bay / Low-bay Light"},
    {1428, "Emergency Exit Light"},
    {1472, "Generic Fan"},
    {1473, "Ceiling Fan"},
    {1474, "Axial Fan"},
    {1475, "Exhaust Fan"},
    {1476, "Pedestal Fan"},
    {1477, "Desk Fan"},
    {1478, "Wall Fan"},
    {1536, "Generic HVAC"},
    {1537, "Thermostat"},
    {1600, "Generic Air Conditioning"},
    {1664, "Generic Humidifier"},
    {1728, "Generic Heating"},
    {1729, "Radiator"},
    {1730, "Boiler"},
    {1731, "Heat Pump"},
    {1732, "Infrared Heater"},
    {1733, "Radiant Panel Heater"},
    {1734, "Fan Heater"},
    {1735, "Air Curtain"},
    {1792, "Generic Access Control"},
    {1793, "Access Door"},
    {1794, "Garage Door"},
    {1795, "Emergency Exit Door"},
    {1796, "Access Lock"},
    {1797, "Elevator"},
    {1798, "Window"},
    {1799, "Entrance Gate"},
    {1856, "Generic Motorized Device"},
    {1857, "Motorized Gate"},
    {1858, "Awning"},
    {1859, "Blinds or Shades"},
    {1860, "Curtains"},
    {1861, "Screen"},
    {1920, "Generic Power Device"},
    {1921, "Power Outlet"},
    {1922, "Power Strip"},
    {1923, "Plug"},
    {1924, "Power Supply"},
    {1925, "LED Driver"},
    {1926, "Fluorescent Lamp Gear"},
    {1927, "HID Lamp Gear"},
    {1984, "Generic Light Source"},
    {1985, "Incandescent Light Bulb"},
    {1986, "LED Bulb"},
    {1987, "HID Lamp"},
    {1988, "Fluorescent Lamp"},
    {1989, "LED Array"},
    {1990, "Multi-Color LED Array"},
    {3136, "Generic: Pulse Oximeter"},
    {3137, "Fingertip"},
    {3138, "Wrist Worn"},
    {3200, "Generic: Weight Scale"},
    {3264, "Generic Personal Mobility Device"},
    {3265, "Powered Wheelchair"},
    {3266, "Mobility Scooter"},
    {3328, "Generic Continuous Glucose Monitor"},
    {5184, "Generic: Outdoor Sports Activity"},
    {5185, "Location Display Device"},
    {5186, "Location and Navigation Display Device"},
    {5187, "Location Pod"},
    {5188, "Location and Navigation Pod"},
};

std::unordered_map<unsigned int, const char *> bt_io_capability{
    {0x00, "Display Only" },
    {0x01, "Display Yes/No" },
    {0x02, "Keyboard Only" },
    {0x03, "No Input, No Output" },
};

