# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdrrtl433.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kismet_pb2 as kismet__pb2
import datasource_pb2 as datasource__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sdrrtl433.proto',
  package='KismetSdrRtl433',
  syntax='proto2',
  serialized_pb=_b('\n\x0fsdrrtl433.proto\x12\x0fKismetSdrRtl433\x1a\x0ckismet.proto\x1a\x10\x64\x61tasource.proto\"\xbb\x01\n\x13SdrRtl433DataReport\x12%\n\x03gps\x18\x01 \x01(\x0b\x32\x18.KismetDatasource.SubGps\x12.\n\x07message\x18\x02 \x01(\x0b\x32\x1d.KismetExternal.MsgbusMessage\x12\x0f\n\x07warning\x18\x03 \x01(\t\x12+\n\x06signal\x18\x04 \x01(\x0b\x32\x1b.KismetDatasource.SubSignal\x12\x0f\n\x07rtljson\x18\x05 \x02(\t')
  ,
  dependencies=[kismet__pb2.DESCRIPTOR,datasource__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SDRRTL433DATAREPORT = _descriptor.Descriptor(
  name='SdrRtl433DataReport',
  full_name='KismetSdrRtl433.SdrRtl433DataReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gps', full_name='KismetSdrRtl433.SdrRtl433DataReport.gps', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='KismetSdrRtl433.SdrRtl433DataReport.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='warning', full_name='KismetSdrRtl433.SdrRtl433DataReport.warning', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signal', full_name='KismetSdrRtl433.SdrRtl433DataReport.signal', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtljson', full_name='KismetSdrRtl433.SdrRtl433DataReport.rtljson', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=256,
)

_SDRRTL433DATAREPORT.fields_by_name['gps'].message_type = datasource__pb2._SUBGPS
_SDRRTL433DATAREPORT.fields_by_name['message'].message_type = kismet__pb2._MSGBUSMESSAGE
_SDRRTL433DATAREPORT.fields_by_name['signal'].message_type = datasource__pb2._SUBSIGNAL
DESCRIPTOR.message_types_by_name['SdrRtl433DataReport'] = _SDRRTL433DATAREPORT

SdrRtl433DataReport = _reflection.GeneratedProtocolMessageType('SdrRtl433DataReport', (_message.Message,), dict(
  DESCRIPTOR = _SDRRTL433DATAREPORT,
  __module__ = 'sdrrtl433_pb2'
  # @@protoc_insertion_point(class_scope:KismetSdrRtl433.SdrRtl433DataReport)
  ))
_sym_db.RegisterMessage(SdrRtl433DataReport)


# @@protoc_insertion_point(module_scope)
