.Dd July 2002
.Dt KISMET.CONF 5
.Os "Kismet"
.Sh NAME
.Nm kismet.conf
.Nd Wireless sniffing and monitoring configuration file
.Sh DESCRIPTION
.Nm kismet
expects a configuration file (/usr/local/etc/kismet.conf by default) which 
should conform to the following rules.  A default configuration is provided with 
.Nm kismet
but it is likely that you will need to modify it to suit your hardware and 
preferences.
.Sh CONFIGURATION FILE FORMAT
All entries are of the format 
directive = value
.Sh SEE ALSO
kismet_ui.conf(5), gpsmap(1), kismet(1), kismet_monitor(1)
