# Meshtastic-specific configuration options
#
# This configuration file is part of the Kismet configuration.  It is loaded
# by the kismet.conf main configuration file.
#
# For more information about the configuration options, see the comments in this
# file and the documentation at:
# https://www.kismetwireless.net/docs/readme/configuring/configfiles/
#
# You can edit the values in these files, but to make it much easier to update Kismet
# in the future, you should put your changes in the kismet_site.conf override file.
# You can learn more about the override config at:
# https://www.kismetwireless.net/docs/readme/configuring/configfiles/#customizing-configs-with-kismet_siteconf

# Multiple meshtastic keys; each channel requires a key.
meshtastic_key=hackercoms,6IzsaoVhx1ETWeWuu0dUWMLqItvYJLbRzwgTAKCfvtY=
meshtastic_key=defconnect,OEu8wB3AItGBvza4YSHh+5a3LlW/dCJ+nWr7SNZMsaE=

