#!/usr/bin/env python2

"""
rtladsb Kismet data source

Implements a rtladsb datasource for Kismet, using the 
KismetCaptureRtladsb Python module

"""

import sys
import time

try:
    import KismetCaptureRtladsb
except ImportError:
    print("Could not import the KismetCaptureRtladsb Python code; you need to install the rest of the rtladsb code from Kismet.")
    sys.exit(0)

if __name__ == '__main__':
    sys.tracebacklimit = 0

    rtl = KismetCaptureRtladsb.KismetRtladsb(mqtt=True)

    # Go into sleep mode
    while rtl.is_running():
        time.sleep(1)

