#!/usr/bin/env python2

"""
rtladsb Kismet data source

Implements a rtladsb datasource for Kismet, using the 
KismetCapturertladsb Python module

"""

import sys
import time

try:
    import KismetCaptureRtladsb
except ImportError as e:
    print("Could not import the KismetCaptureRtladsb Python code; you are likely missing")
    print("a Python dependency or the KismetCaptureRtladsb python module is not installed:")
    print(e)
    sys.exit(0)

if __name__ == '__main__':
    sys.tracebacklimit = 0

    rtl = KismetCaptureRtladsb.KismetRtladsb()

    # Go into sleep mode
    while rtl.is_running():
        time.sleep(1)

