/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: http.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "http.pb-c.h"
void   kismet_external_http__http_auth_token__init
                     (KismetExternalHttp__HttpAuthToken         *message)
{
  static KismetExternalHttp__HttpAuthToken init_value = KISMET_EXTERNAL_HTTP__HTTP_AUTH_TOKEN__INIT;
  *message = init_value;
}
size_t kismet_external_http__http_auth_token__get_packed_size
                     (const KismetExternalHttp__HttpAuthToken *message)
{
  assert(message->base.descriptor == &kismet_external_http__http_auth_token__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kismet_external_http__http_auth_token__pack
                     (const KismetExternalHttp__HttpAuthToken *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kismet_external_http__http_auth_token__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kismet_external_http__http_auth_token__pack_to_buffer
                     (const KismetExternalHttp__HttpAuthToken *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kismet_external_http__http_auth_token__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KismetExternalHttp__HttpAuthToken *
       kismet_external_http__http_auth_token__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KismetExternalHttp__HttpAuthToken *)
     protobuf_c_message_unpack (&kismet_external_http__http_auth_token__descriptor,
                                allocator, len, data);
}
void   kismet_external_http__http_auth_token__free_unpacked
                     (KismetExternalHttp__HttpAuthToken *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &kismet_external_http__http_auth_token__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kismet_external_http__http_register_uri__init
                     (KismetExternalHttp__HttpRegisterUri         *message)
{
  static KismetExternalHttp__HttpRegisterUri init_value = KISMET_EXTERNAL_HTTP__HTTP_REGISTER_URI__INIT;
  *message = init_value;
}
size_t kismet_external_http__http_register_uri__get_packed_size
                     (const KismetExternalHttp__HttpRegisterUri *message)
{
  assert(message->base.descriptor == &kismet_external_http__http_register_uri__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kismet_external_http__http_register_uri__pack
                     (const KismetExternalHttp__HttpRegisterUri *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kismet_external_http__http_register_uri__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kismet_external_http__http_register_uri__pack_to_buffer
                     (const KismetExternalHttp__HttpRegisterUri *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kismet_external_http__http_register_uri__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KismetExternalHttp__HttpRegisterUri *
       kismet_external_http__http_register_uri__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KismetExternalHttp__HttpRegisterUri *)
     protobuf_c_message_unpack (&kismet_external_http__http_register_uri__descriptor,
                                allocator, len, data);
}
void   kismet_external_http__http_register_uri__free_unpacked
                     (KismetExternalHttp__HttpRegisterUri *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &kismet_external_http__http_register_uri__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kismet_external_http__http_request__post_data_entry__init
                     (KismetExternalHttp__HttpRequest__PostDataEntry         *message)
{
  static KismetExternalHttp__HttpRequest__PostDataEntry init_value = KISMET_EXTERNAL_HTTP__HTTP_REQUEST__POST_DATA_ENTRY__INIT;
  *message = init_value;
}
void   kismet_external_http__http_request__init
                     (KismetExternalHttp__HttpRequest         *message)
{
  static KismetExternalHttp__HttpRequest init_value = KISMET_EXTERNAL_HTTP__HTTP_REQUEST__INIT;
  *message = init_value;
}
size_t kismet_external_http__http_request__get_packed_size
                     (const KismetExternalHttp__HttpRequest *message)
{
  assert(message->base.descriptor == &kismet_external_http__http_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kismet_external_http__http_request__pack
                     (const KismetExternalHttp__HttpRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kismet_external_http__http_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kismet_external_http__http_request__pack_to_buffer
                     (const KismetExternalHttp__HttpRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kismet_external_http__http_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KismetExternalHttp__HttpRequest *
       kismet_external_http__http_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KismetExternalHttp__HttpRequest *)
     protobuf_c_message_unpack (&kismet_external_http__http_request__descriptor,
                                allocator, len, data);
}
void   kismet_external_http__http_request__free_unpacked
                     (KismetExternalHttp__HttpRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &kismet_external_http__http_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kismet_external_http__http_response__header_content_entry__init
                     (KismetExternalHttp__HttpResponse__HeaderContentEntry         *message)
{
  static KismetExternalHttp__HttpResponse__HeaderContentEntry init_value = KISMET_EXTERNAL_HTTP__HTTP_RESPONSE__HEADER_CONTENT_ENTRY__INIT;
  *message = init_value;
}
void   kismet_external_http__http_response__init
                     (KismetExternalHttp__HttpResponse         *message)
{
  static KismetExternalHttp__HttpResponse init_value = KISMET_EXTERNAL_HTTP__HTTP_RESPONSE__INIT;
  *message = init_value;
}
size_t kismet_external_http__http_response__get_packed_size
                     (const KismetExternalHttp__HttpResponse *message)
{
  assert(message->base.descriptor == &kismet_external_http__http_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kismet_external_http__http_response__pack
                     (const KismetExternalHttp__HttpResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kismet_external_http__http_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kismet_external_http__http_response__pack_to_buffer
                     (const KismetExternalHttp__HttpResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kismet_external_http__http_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KismetExternalHttp__HttpResponse *
       kismet_external_http__http_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KismetExternalHttp__HttpResponse *)
     protobuf_c_message_unpack (&kismet_external_http__http_response__descriptor,
                                allocator, len, data);
}
void   kismet_external_http__http_response__free_unpacked
                     (KismetExternalHttp__HttpResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &kismet_external_http__http_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor kismet_external_http__http_auth_token__field_descriptors[1] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpAuthToken, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kismet_external_http__http_auth_token__field_indices_by_name[] = {
  0,   /* field[0] = token */
};
static const ProtobufCIntRange kismet_external_http__http_auth_token__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor kismet_external_http__http_auth_token__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KismetExternalHttp.HttpAuthToken",
  "HttpAuthToken",
  "KismetExternalHttp__HttpAuthToken",
  "KismetExternalHttp",
  sizeof(KismetExternalHttp__HttpAuthToken),
  1,
  kismet_external_http__http_auth_token__field_descriptors,
  kismet_external_http__http_auth_token__field_indices_by_name,
  1,  kismet_external_http__http_auth_token__number_ranges,
  (ProtobufCMessageInit) kismet_external_http__http_auth_token__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kismet_external_http__http_register_uri__field_descriptors[3] =
{
  {
    "uri",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpRegisterUri, uri),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpRegisterUri, method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_required",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpRegisterUri, auth_required),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kismet_external_http__http_register_uri__field_indices_by_name[] = {
  2,   /* field[2] = auth_required */
  1,   /* field[1] = method */
  0,   /* field[0] = uri */
};
static const ProtobufCIntRange kismet_external_http__http_register_uri__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor kismet_external_http__http_register_uri__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KismetExternalHttp.HttpRegisterUri",
  "HttpRegisterUri",
  "KismetExternalHttp__HttpRegisterUri",
  "KismetExternalHttp",
  sizeof(KismetExternalHttp__HttpRegisterUri),
  3,
  kismet_external_http__http_register_uri__field_descriptors,
  kismet_external_http__http_register_uri__field_indices_by_name,
  1,  kismet_external_http__http_register_uri__number_ranges,
  (ProtobufCMessageInit) kismet_external_http__http_register_uri__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kismet_external_http__http_request__post_data_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpRequest__PostDataEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpRequest__PostDataEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kismet_external_http__http_request__post_data_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange kismet_external_http__http_request__post_data_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kismet_external_http__http_request__post_data_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KismetExternalHttp.HttpRequest.PostDataEntry",
  "PostDataEntry",
  "KismetExternalHttp__HttpRequest__PostDataEntry",
  "KismetExternalHttp",
  sizeof(KismetExternalHttp__HttpRequest__PostDataEntry),
  2,
  kismet_external_http__http_request__post_data_entry__field_descriptors,
  kismet_external_http__http_request__post_data_entry__field_indices_by_name,
  1,  kismet_external_http__http_request__post_data_entry__number_ranges,
  (ProtobufCMessageInit) kismet_external_http__http_request__post_data_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kismet_external_http__http_request__field_descriptors[4] =
{
  {
    "req_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpRequest, req_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uri",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpRequest, uri),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpRequest, method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "post_data",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(KismetExternalHttp__HttpRequest, n_post_data),
    offsetof(KismetExternalHttp__HttpRequest, post_data),
    &kismet_external_http__http_request__post_data_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kismet_external_http__http_request__field_indices_by_name[] = {
  2,   /* field[2] = method */
  3,   /* field[3] = post_data */
  0,   /* field[0] = req_id */
  1,   /* field[1] = uri */
};
static const ProtobufCIntRange kismet_external_http__http_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor kismet_external_http__http_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KismetExternalHttp.HttpRequest",
  "HttpRequest",
  "KismetExternalHttp__HttpRequest",
  "KismetExternalHttp",
  sizeof(KismetExternalHttp__HttpRequest),
  4,
  kismet_external_http__http_request__field_descriptors,
  kismet_external_http__http_request__field_indices_by_name,
  1,  kismet_external_http__http_request__number_ranges,
  (ProtobufCMessageInit) kismet_external_http__http_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kismet_external_http__http_response__header_content_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpResponse__HeaderContentEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpResponse__HeaderContentEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kismet_external_http__http_response__header_content_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange kismet_external_http__http_response__header_content_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kismet_external_http__http_response__header_content_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KismetExternalHttp.HttpResponse.HeaderContentEntry",
  "HeaderContentEntry",
  "KismetExternalHttp__HttpResponse__HeaderContentEntry",
  "KismetExternalHttp",
  sizeof(KismetExternalHttp__HttpResponse__HeaderContentEntry),
  2,
  kismet_external_http__http_response__header_content_entry__field_descriptors,
  kismet_external_http__http_response__header_content_entry__field_indices_by_name,
  1,  kismet_external_http__http_response__header_content_entry__number_ranges,
  (ProtobufCMessageInit) kismet_external_http__http_response__header_content_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kismet_external_http__http_response__field_descriptors[5] =
{
  {
    "req_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(KismetExternalHttp__HttpResponse, req_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header_content",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(KismetExternalHttp__HttpResponse, n_header_content),
    offsetof(KismetExternalHttp__HttpResponse, header_content),
    &kismet_external_http__http_response__header_content_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(KismetExternalHttp__HttpResponse, has_content),
    offsetof(KismetExternalHttp__HttpResponse, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resultcode",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(KismetExternalHttp__HttpResponse, has_resultcode),
    offsetof(KismetExternalHttp__HttpResponse, resultcode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "close_response",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(KismetExternalHttp__HttpResponse, has_close_response),
    offsetof(KismetExternalHttp__HttpResponse, close_response),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kismet_external_http__http_response__field_indices_by_name[] = {
  4,   /* field[4] = close_response */
  2,   /* field[2] = content */
  1,   /* field[1] = header_content */
  0,   /* field[0] = req_id */
  3,   /* field[3] = resultcode */
};
static const ProtobufCIntRange kismet_external_http__http_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor kismet_external_http__http_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KismetExternalHttp.HttpResponse",
  "HttpResponse",
  "KismetExternalHttp__HttpResponse",
  "KismetExternalHttp",
  sizeof(KismetExternalHttp__HttpResponse),
  5,
  kismet_external_http__http_response__field_descriptors,
  kismet_external_http__http_response__field_indices_by_name,
  1,  kismet_external_http__http_response__number_ranges,
  (ProtobufCMessageInit) kismet_external_http__http_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
