#!/usr/bin/env python2

"""
rtl_433 Kismet data source

Implements a rtl_433 datasource for Kismet, using the 
KismetCaptureRtl433 Python module

"""

import sys
import time

try:
    import KismetCaptureRtl433
except ImportError as e:
    print("Could not import the KismetCaptureRtl433 Python code; you are likely missing")
    print("a Python dependency or the KismetCaptureRtl433 python module is not installed:")
    print(e)
    sys.exit(0)

if __name__ == '__main__':
    sys.tracebacklimit = 0

    rtl = KismetCaptureRtl433.KismetRtl433(mqtt=True)

    # Go into sleep mode
    while rtl.is_running():
        time.sleep(1)

