#!/usr/bin/env python2

import argparse
import time

import KismetExternal

# Callback function for handling a req of our python.html endpoint
def handle_web_python(externalhandler, request):
    print "PYTHON - Handle web req {} {} {}".format(request.req_id, request.method, request.uri)
    externalhandler.send_http_response(request.req_id, "<html><body><b>This is from python!</b></body></html>")

parser = argparse.ArgumentParser(description='Kismet External Python Example')

parser.add_argument('--in-fd', action="store", type=int, dest="infd")
parser.add_argument('--out-fd', action="store", type=int, dest="outfd")

results = parser.parse_args()

print "PYTHON PROXYTEST - KEI got infd {} outfd {}".format(results.infd, results.outfd)

kei = KismetExternal.KismetExternalInterface(results.infd, results.outfd)

kei.start()

# Add a URI that doesn't need a login
kei.add_uri_handler("GET", "/proxytest/python.html", False, handle_web_python)

while True and kei.is_running():
    kei.send_ping()
    time.sleep(1)

kei.kill()

