#!/usr/bin/env python2

"""
rtlamr Kismet data source

Implements a rtlamr datasource for Kismet, using the 
KismetCapturertlamr Python module

"""

import sys
import time

try:
    import KismetCaptureRtlamr
except ImportError:
    print("Could not import the KismetCaptureRtlamr Python code; you need to install the rest of the rtlamr code from Kismet.")
    sys.exit(0)

if __name__ == '__main__':
    sys.tracebacklimit = 0

    rtl = KismetCaptureRtlamr.KismetRtlamr()

    # Go into sleep mode
    while rtl.is_running():
        time.sleep(1)

