#!/usr/bin/env python2

"""
rtlamr Kismet data source

Implements a rtlamr datasource for Kismet, using the 
KismetCapturertlamr Python module

"""

import sys
import time

try:
    import KismetCaptureRtlamr
except ImportError as e:
    print("Could not import the KismetCaptureRtlamr Python code; you are likely missing")
    print("a Python dependency or the KismetCaptureRtlamr python module is not installed:")
    print(e)
    sys.exit(0)

if __name__ == '__main__':
    sys.tracebacklimit = 0

    rtl = KismetCaptureRtlamr.KismetRtlamr()

    # Go into sleep mode
    while rtl.is_running():
        time.sleep(1)

