#!/bin/sh -e

# Copied from wireshark-common and modified

. /usr/share/debconf/confmodule
db_get kismet/install-setuid
PROGRAM=/usr/bin/kismet_capture
GROUP=kismet

if [ -e "$PROGRAM" ]; then
    if [ "$RET" = "false" ] ; then
         if [ -x /usr/sbin/dpkg-statoverride ] && \
             ! /usr/sbin/dpkg-statoverride --list $PROGRAM >/dev/null; then
             chown root:root $PROGRAM
             chmod u=rwx,go=rx $PROGRAM
         fi
    else
        if [ -x /usr/sbin/dpkg-statoverride ] && \
            ! /usr/sbin/dpkg-statoverride --list $PROGRAM >/dev/null; then
            addgroup --quiet --system $GROUP
            chown root:$GROUP $PROGRAM
            if which setcap > /dev/null ; then
                chmod u=rwx,g=rx,o=r $PROGRAM
                if ! setcap cap_net_raw,cap_net_admin=eip $PROGRAM; then
                    echo "Setting capabilities for kismet_capture using Linux Capabilities failed."
                    echo "Falling back to setting set-user-id bit."
                    chmod u=rwxs,g=rx,o=r $PROGRAM
                fi
            else
                chmod u=rwxs,g=rx,o=r $PROGRAM
            fi
        fi
    fi
fi


