#include "../config.h"

#ifndef __RZ_KILLERBEE_H__
#define __RZ_KILLERBEE_H__

#define RZ_KILLERBEE_USB_VENDOR		0x03EB 
#define RZ_KILLERBEE_USB_PRODUCT	0x210A 

#define RZ_KILLERBEE_SET_MODE		0x07
#define RZ_KILLERBEE_SET_CHANNEL	0x08
#define RZ_KILLERBEE_OPEN_STREAM	0x09
#define RZ_KILLERBEE_CLOSE_STREAM	0x0A

#define RZ_KILLERBEE_CMD_MODE_AC	0x00
#define RZ_KILLERBEE_CMD_MODE_NONE	0x04

#define RZ_KILLERBEE_CMD_GET_IDENT	0xC0
#define RZ_KILLERBEE_CMD_DIR_IN 	0xC0

#define RZ_KILLERBEE_CMD_EP		    0x02
#define RZ_KILLERBEE_REP_EP		    0x84
#define RZ_KILLERBEE_PKT_EP		    0x81

#define RZ_KILLERBEE_CMD_TIMEOUT	    100
#define RZ_KILLERBEE_READ_TIMEOUT       200
#endif

