#!/usr/bin/env python3

"""
Freaklabs Zigbee Kismet Datasource

"""

import sys
import time

try:
    import KismetCaptureFreaklabsZigbee
except ImportError:
    print("Could not import the KismetCaptureFreaklabsZigbee Python code; you need to install ")
    print("the rest of the support code from Kismet.")
    sys.exit(0)

if __name__ == '__main__':
    sys.tracebacklimit = 0

    zig = KismetCaptureFreaklabsZigbee.KismetFreaklabsZigbee()

    # Go into sleep mode
    while zig.is_running():
        time.sleep(1)

