#!/usr/bin/env python2

"""
Freaklabs Zigbee Kismet Datasource

"""

import sys
import time

try:
    import KismetCaptureFreaklabsZigbee
except ImportError as e:
    print("Could not import the KismetCaptureFreaklabsZigbee Python code; you are likely missing")
    print("a Python dependency or the KismetCaptureFreaklabsZigbee python module is not installed:")
    print(e)
    sys.exit(0)

if __name__ == '__main__':
    sys.tracebacklimit = 0

    zig = KismetCaptureFreaklabsZigbee.KismetFreaklabsZigbee()

    # Go into sleep mode
    while zig.is_running():
        time.sleep(1)

