name: Codespell

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codespell:
    name: Codespell spell checker
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install codespell
        run: sudo apt update -y && sudo apt install -y codespell

      - name: Run codespell
        run: codespell
