name: Ubuntu All No WEXT Build Test

on: [push, pull_request]

jobs:
  ubuntu-all-no-wext-build-test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    -
      name: List added files
      run: git --no-pager diff --name-only "$(git rev-parse --verify origin/master 2> /dev/null)" HEAD
    -
      name: Builder
      env:
          WORKSPACE: ${{ github.workspace }}
      run: |
          docker run -v "/var/run/docker.sock":"/var/run/docker.sock" \
              --entrypoint /all-no-wext-build.sh \
              -v ${WORKSPACE}:/github/workspace \
              ghcr.io/kismetwireless/kismet/build-ubuntu-noble-amd64:latest

